### ISSUE TITLE
Some radios works on ios but not working on android

### ISSUE THREAD

**Issue by iballan** [cheebeez/radio_player#14]
An example of links that are not working on android:

http://104.7.66.64:8091/;?icy=http

I got this log:

```

I/flutter ( 8380): PlatformException(error, ComponentName does not belong to sessionPackageName. sessionPackageName = com.my.package, ComponentName pkg = com.google.android.apps.youtube.music, null, java.lang.IllegalArgumentException: ComponentName does not belong to sessionPackageName. sessionPackageName = com.my.package, ComponentName pkg = com.google.android.apps.youtube.music
I/flutter ( 8380): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
I/flutter ( 8380): 	at android.os.Parcel.createException(Parcel.java:2995)
I/flutter ( 8380): 	at android.os.Parcel.readException(Parcel.java:2978)
I/flutter ( 8380): 	at android.os.Parcel.readException(Parcel.java:2920)
I/flutter ( 8380): 	at android.media.session.ISession$Stub$Proxy.setMediaButtonReceiver(ISession.java:466)
I/flutter ( 8380): 	at android.media.session.MediaSession.setMediaButtonReceiver(MediaSession.java:289)
I/flutter ( 8380): 	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi21.setMediaButtonReceiver(MediaSessionCompat.java:3965)
I/flutter ( 8380): 	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:588)
I/flutter ( 8380): 	at android.support.v
I/flutter ( 8380): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
I/flutter ( 8380): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
I/flutter ( 8380): <asynchronous suspension>
I/flutter ( 8380): #2      RadioPlayer.setChannel (package:radio_player/radio_player.dart:28:5)
I/flutter ( 8380): <asynchronous suspension>
I/flutter ( 8380): #3      RadioService.playRadio (package:pt/services/RadioService.dart:54:5)
I/flutter ( 8380): <asynchronous suspension>
I/flutter ( 8380): #4      _RadioPageState._buildBody.<anonymous closure>.<anonymous closure> (package:pt/ui/live/radio_page.dart:107:13)
I/flutter ( 8380): <asynchronous suspension>
I/flutter ( 8380): ----------------------------------------------------
```

**Comment by iballan** [comment]
Thank you for your reply,
I will try to test on different devices though
