### ISSUE TITLE
[Feature Request] Callback for Source Error

### ISSUE THREAD

**Issue by fairuzmn** [cheebeez/radio_player#23]
hi @cheebeez

so sometimes the streaming source is not online, it's not caused app crashing anyway but
is there any change for this package to have callback for source error?

btw, thanks for making this great package

```
E/ExoPlayerImplInternal(12215): Playback error
E/ExoPlayerImplInternal(12215):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(12215):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
E/ExoPlayerImplInternal(12215):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:614)
E/ExoPlayerImplInternal(12215):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(12215):       at android.os.Looper.loopOnce(Looper.java:201)
E/ExoPlayerImplInternal(12215):       at android.os.Looper.loop(Looper.java:288)
E/ExoPlayerImplInternal(12215):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(12215):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, AviExtractor, JpegExtractor) could read the stream.
E/ExoPlayerImplInternal(12215):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal(12215):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1017)
E/ExoPlayerImplInternal(12215):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(12215):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/ExoPlayerImplInternal(12215):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/ExoPlayerImplInternal(12215):       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by rodrigoti** [comment]
mesma sugestão, como escutar na função 'ouvir' o status da mídia se offline?

**Comment by rodrigoti** [comment]
same suggestion, how to listen in 'listen' function to media status if offline?
