### ISSUE TITLE
[upgrade] replace deprecated ExoPlayer 

### ISSUE THREAD

**Issue by renanyoy** [cheebeez/radio_player#38]
[androidx.media3:media3-exoplayer](https://developer.android.com/jetpack/androidx/releases/media3)

**Comment by sukhi-23** [comment]
E/ExoPlayerImplInternal( 6211): Playback error
E/ExoPlayerImplInternal( 6211):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 6211):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
E/ExoPlayerImplInternal( 6211):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:656)
E/ExoPlayerImplInternal( 6211):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 6211):       at android.os.Looper.loop(Looper.java:246)
E/ExoPlayerImplInternal( 6211):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 6211):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
E/ExoPlayerImplInternal( 6211):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:419)
E/ExoPlayerImplInternal( 6211):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:269)
E/ExoPlayerImplInternal( 6211):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:90)
E/ExoPlayerImplInternal( 6211):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1013)
E/ExoPlayerImplInternal( 6211):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420)
E/ExoPlayerImplInternal( 6211):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 6211):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 6211):       at java.lang.Thread.run(Thread.java:923)


I am not able to understand how to resolve this error ?
